//! DPI and UI scaling for X11.
//!
//! X11 doesn't have native HiDPI scaling like Wayland. Scaling is achieved by:
//! 1. xsettingsd for GTK applications (Gdk/WindowScalingFactor)
//! 2. Xft.dpi via X resources (affects fonts and DPI-aware apps)
//!
//! IMPORTANT: On X11, scaling changes typically require apps to be restarted
//! (or logout/login) to fully take effect. This is a fundamental X11 limitation.

use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

/// Base DPI (96 is the X11 standard).
const BASE_DPI: u32 = 96;

/// Get the xsettingsd config file path.
fn xsettingsd_config_path() -> PathBuf {
    let runtime_dir =
        std::env::var("XDG_RUNTIME_DIR").unwrap_or_else(|_| "/tmp".to_string());
    PathBuf::from(runtime_dir).join("gardisplay-xsettingsd.conf")
}

/// Write the xsettingsd configuration file.
fn write_xsettingsd_config(scale: f64) -> std::io::Result<PathBuf> {
    let config_path = xsettingsd_config_path();

    let scale_factor = scale.round() as u32;
    let dpi = (BASE_DPI as f64 * scale).round() as u32;

    // xsettingsd uses fixed-point format: value * 1024
    let xft_dpi_fixed = dpi * 1024;
    let unscaled_dpi_fixed = BASE_DPI * 1024;

    let config = format!(
        r#"# Generated by gardisplay
Gdk/WindowScalingFactor {scale_factor}
Gdk/UnscaledDPI {unscaled_dpi_fixed}
Xft/DPI {xft_dpi_fixed}
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
"#
    );

    let mut file = fs::File::create(&config_path)?;
    file.write_all(config.as_bytes())?;
    file.sync_all()?;

    tracing::debug!("wrote xsettingsd config to {:?}", config_path);
    Ok(config_path)
}

/// Check if xsettingsd is running and return its PID.
fn get_xsettingsd_pid() -> Option<u32> {
    let output = Command::new("pgrep")
        .arg("-x")
        .arg("xsettingsd")
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    stdout.trim().parse().ok()
}

/// Start xsettingsd if not running, or send SIGHUP to reload config.
fn start_or_reload_xsettingsd(config_path: &PathBuf) -> std::io::Result<()> {
    if let Some(pid) = get_xsettingsd_pid() {
        // Send SIGHUP to reload config (gentler than restart)
        tracing::info!("sending SIGHUP to xsettingsd (PID {})", pid);
        let _ = Command::new("kill")
            .arg("-HUP")
            .arg(pid.to_string())
            .status();
    } else {
        // Start xsettingsd
        tracing::info!("starting xsettingsd with config {:?}", config_path);
        Command::new("xsettingsd")
            .arg("-c")
            .arg(config_path)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()?;
    }

    Ok(())
}

/// Apply DPI scaling via xrdb (for legacy X11 apps).
fn apply_xrdb_dpi(dpi: u32) -> std::io::Result<()> {
    let resource = format!("Xft.dpi: {}\n", dpi);

    let mut child = Command::new("xrdb")
        .arg("-merge")
        .stdin(std::process::Stdio::piped())
        .spawn()?;

    if let Some(mut stdin) = child.stdin.take() {
        stdin.write_all(resource.as_bytes())?;
    }

    child.wait()?;
    Ok(())
}

/// Apply DPI scaling for the desktop.
/// This sets up both xsettingsd (for GTK apps) and xrdb (for legacy apps).
/// Scale of 1.0 = 96 DPI, scale of 2.0 = 192 DPI, etc.
///
/// NOTE: Existing applications may not fully update until restarted.
/// This is a fundamental X11 limitation.
pub fn apply_dpi_scale(scale: f64) -> std::io::Result<()> {
    let dpi = (BASE_DPI as f64 * scale).round() as u32;
    let scale_factor = scale.round() as u32;

    tracing::info!(
        "applying scale {} (DPI={}, WindowScalingFactor={})",
        scale,
        dpi,
        scale_factor
    );

    // 1. Write xsettingsd config and reload
    if let Ok(config_path) = write_xsettingsd_config(scale) {
        if let Err(e) = start_or_reload_xsettingsd(&config_path) {
            tracing::warn!("failed to start/reload xsettingsd: {}", e);
        }
    }

    // 2. Apply xrdb DPI for legacy apps
    if let Err(e) = apply_xrdb_dpi(dpi) {
        tracing::warn!("failed to set xrdb DPI: {}", e);
    }

    tracing::info!("scaling applied - new apps will use scale {}", scale);
    Ok(())
}

/// Get the current DPI setting from xrdb.
#[allow(dead_code)] // Available for supplemental DPI queries
pub fn get_current_dpi() -> Option<u32> {
    let output = Command::new("xrdb").arg("-query").output().ok()?;

    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines() {
        if line.starts_with("Xft.dpi:") {
            let parts: Vec<&str> = line.split(':').collect();
            if parts.len() == 2 {
                return parts[1].trim().parse().ok();
            }
        }
    }

    None
}

/// Get the current scale factor based on DPI.
#[allow(dead_code)] // Available for supplemental DPI queries
pub fn get_current_scale() -> f64 {
    get_current_dpi()
        .map(|dpi| dpi as f64 / BASE_DPI as f64)
        .unwrap_or(1.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dpi_calculation() {
        assert_eq!((BASE_DPI as f64 * 1.0).round() as u32, 96);
        assert_eq!((BASE_DPI as f64 * 1.5).round() as u32, 144);
        assert_eq!((BASE_DPI as f64 * 2.0).round() as u32, 192);
    }

    #[test]
    fn test_xsettingsd_config_path() {
        let path = xsettingsd_config_path();
        assert!(path.to_string_lossy().contains("gardisplay-xsettingsd"));
    }
}
